services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go

  mongo:
    image: mongo:6
    container_name: user-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: